# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pipeline_pb2 as pipeline__pb2


class YoloV5Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detect = channel.unary_unary(
        '/YoloV5/detect',
        request_serializer=pipeline__pb2.Image.SerializeToString,
        response_deserializer=pipeline__pb2.DetectedObjects.FromString,
        )


class YoloV5Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YoloV5Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detect': grpc.unary_unary_rpc_method_handler(
          servicer.detect,
          request_deserializer=pipeline__pb2.Image.FromString,
          response_serializer=pipeline__pb2.DetectedObjects.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YoloV5', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class VisualizationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Visualize = channel.unary_unary(
        '/VisualizationService/Visualize',
        request_serializer=pipeline__pb2.ImageWithObjects.SerializeToString,
        response_deserializer=pipeline__pb2.Empty.FromString,
        )


class VisualizationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Visualize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VisualizationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Visualize': grpc.unary_unary_rpc_method_handler(
          servicer.Visualize,
          request_deserializer=pipeline__pb2.ImageWithObjects.FromString,
          response_serializer=pipeline__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'VisualizationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
